In [12]:
import numpy as np

X=np.array(([2,9],[1,5],[3,6]),dtype=float)

y=np.array(([92],[86],[89]),dtype=float)

X=X/np.amax(X,axis=0)	#maximumofXaraylongitudinaly

y=y/100

#SigmoidFunction

def sigmoid(x):
   return 1/(1+np.exp(-x))
 


 

#DerivativeofSigmoidFunction

def derivatives_sigmoid(x):

    return x*(1-x)

#Variableinitialization

epoch=5	#Setingtrainingiterations


lr=0.1	#Setinglearningrate

inputlayer_neurons=2	#numberoffeaturesindataset

hiddenlayer_neurons=3	#numberofhiddenlayersneurons

output_neurons=1	#numberofneuronsatoutputlayer

#weightandbiasinitialization

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))

bh=np.random.uniform(size=(1,hiddenlayer_neurons))

wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))

bout=np.random.uniform(size=(1,output_neurons)) #drawsarandomrangeofnumbersuniformlyofdimx*y 
for i in range(epoch):

            #ForwardPropogation

            hinp1=np.dot(X,wh)

            hinp=hinp1+bh

            hlayer_act=sigmoid(hinp)

            outinp1=np.dot(hlayer_act,wout)

            outinp=outinp1+bout

            output=sigmoid(outinp)

            #Backpropagation

            EO=y-output

            outgrad=derivatives_sigmoid(output)

            d_output=EO*outgrad

            EH=d_output.dot(wout.T)

            hiddengrad=derivatives_sigmoid(hlayer_act)#howmuchhiddenlayerwtscontribute dtoerror

            d_hiddenlayer=EH*hiddengrad

            wout+=hlayer_act.T.dot(d_output)*lr#dotproductofnextlayererorandcurentla yerop

            wh+=X.T.dot(d_hiddenlayer)*lr

            print("	-Epoch-",i+1,"Starts	-")

            print("Input:\n"+str(X))

            print("ActualOutput:\n"+str(y))

            print("PredictedOutput:\n",output)

            print("	-Epoch-",i+1,"Ends	-\n")

            print("Input:\n"+str(X))

            print("ActualOutput:\n"+str(y))

            print("PredictedOutput:\n",output)



	-Epoch- 1 Starts	-
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ActualOutput:
[[0.92]
 [0.86]
 [0.89]]
PredictedOutput:
 [[0.79692285]
 [0.77295743]
 [0.79784293]]
	-Epoch- 1 Ends	-

Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ActualOutput:
[[0.92]
 [0.86]
 [0.89]]
PredictedOutput:
 [[0.79692285]
 [0.77295743]
 [0.79784293]]
	-Epoch- 2 Starts	-
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ActualOutput:
[[0.92]
 [0.86]
 [0.89]]
PredictedOutput:
 [[0.79845417]
 [0.77443045]
 [0.79941462]]
	-Epoch- 2 Ends	-

Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ActualOutput:
[[0.92]
 [0.86]
 [0.89]]
PredictedOutput:
 [[0.79845417]
 [0.77443045]
 [0.79941462]]
	-Epoch- 3 Starts	-
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ActualOutput:
[[0.92]
 [0.86]
 [0.89]]
PredictedOutput:
 [[0.79994618]
 [0.77586709]
 [